spring.application.name=sideproject
spring.datasource.url=jdbc:oracle:thin:@//yyyproject.tplinkdns.com:1521/XEPDB1
spring.datasource.username=IORDJY
spring.datasource.password=iordjy
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect