apiVersion: apps/v1
kind: Deployment
metadata:
  name: sideproject
  namespace: sideproject
  labels:
    app: sideproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sideproject
  template:
    metadata:
      labels:
        app: sideproject
    spec:
      containers:
        - name: sideproject
          image: ghcr.io/ajy4606/yyy:sha-a073b5bafa7e464a8410c73a836192ab86ad924a
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8081
          envFrom:
            - secretRef:
                name: sideproject-db
          env:
            - name: SERVER_PORT
              value: "8081"
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=70.0"
          startupProbe:
            tcpSocket:
              port: http
            periodSeconds: 5
            failureThreshold: 24
          readinessProbe:
            tcpSocket:
              port: http
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            tcpSocket:
              port: http
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 512Mi
