spring.application.name=sideproject
server.port=8081

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xepdb1
spring.datasource.username=IORDJY
spring.datasource.password=iordjy

## 2. JPA 설정 (다시 추가)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

## 3. MyBatis 설정
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.yyy.sideproject.dto

#logging.level.com.yyy.sideproject.mapper=debug
#logging.level.org.mybatis=debug

mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl